# Import pandas Library

In [10]:
import pandas as pd
df=pd.read_csv(r"C:\Users\Sai Kumar\Documents\pandas\Telecom_DataSet\indian_customers_original.csv")

# Import Dataset to Pandas

In [11]:
import numpy as np
import pandas as pd

# TO Display First 5 Rows

In [12]:

df.head()

,customer_id,name,phone,gender,age,city,state,pincode,city_tier,profession,...,support_calls_last_month,network_satisfaction,price_satisfaction,overall_satisfaction,competitor_offers_received,price_sensitivity_score,is_festival_season,monsoon_impact,churn_probability,churn
0,IND000001,Arjun Bhatt,918332181960,Male,37,Indore,Maharashtra,198246,Tier 2,Student,...,0,1,3,2,1,4,False,False,0.683,Yes
1,IND000002,Kavya Bose,918940781618,Female,44,Kolkata,West Bengal,969693,Tier 1,Government Employee,...,0,4,2,5,2,3,False,False,0.498,Yes
2,IND000003,Ramesh Desai,917832764835,Male,25,Bhopal,Maharashtra,340174,Tier 2,Business Owner,...,1,6,4,9,5,8,False,False,0.657,Yes
3,IND000004,Geeta Tiwari,919532871012,Female,43,Faridabad,Maharashtra,930555,Tier 2,Government Employee,...,0,6,2,9,0,5,False,False,0.489,No
4,IND000005,Shubham Das,917252880957,Male,26,Mumbai,Maharashtra,217301,Tier 1,Private Employee,...,0,2,9,10,3,9,False,False,0.266,No

# TO Display last 5 Rows

In [13]:
df.tail()

,customer_id,name,phone,gender,age,city,state,pincode,city_tier,profession,...,support_calls_last_month,network_satisfaction,price_satisfaction,overall_satisfaction,competitor_offers_received,price_sensitivity_score,is_festival_season,monsoon_impact,churn_probability,churn
9995,IND009996,Vidya Nair,917283879136,Female,27,Kanpur,Uttar Pradesh,727121,Tier 1,Others,...,2,1,5,4,0,3,False,False,0.759,No
9996,IND009997,Tanya Srivastava,918676671709,Female,33,Chennai,Tamil Nadu,832775,Tier 1,IT Professional,...,1,1,8,9,4,5,False,False,0.428,No
9997,IND009998,Rashmi Bose,918847918775,Female,31,Mumbai,Maharashtra,410224,Tier 1,Private Employee,...,0,6,3,9,1,1,False,False,0.273,No
9998,IND009999,Geeta Shah,918341918559,Female,29,Vasai,Maharashtra,673815,Tier 2,Retired,...,1,5,2,10,0,5,False,False,0.243,No
9999,IND010000,Alok Trivedi,918660073115,Male,31,Gorakhpur,Maharashtra,342281,Tier 3,Retired,...,2,8,8,3,2,10,False,False,0.230,No

# To display no of first rows

In [14]:
#df.head(10)

# To Display no of last rows

In [15]:
#df.tail(10)

# To Display Max Rows

In [16]:
pd.set_option('display.max_rows',50)

# To Display Max Columns

In [17]:
pd.set_option('display.max_columns',50)

# TO see all columns

In [18]:
df.columns

Index(['customer_id', 'name', 'phone', 'gender', 'age', 'city', 'state',
       'pincode', 'city_tier', 'profession', 'annual_income_lakhs',
       'is_married', 'has_children', 'num_dependents', 'operator', 'plan_type',
       'monthly_charges', 'is_prepaid', 'tenure_months', 'total_charges',
       'data_usage_gb', 'voice_minutes', 'sms_count', 'has_internet',
       'has_ott_bundle', 'payment_method', 'payment_delays_last_6m',
       'primary_language', 'prefers_regional_support',
       'support_calls_last_month', 'network_satisfaction',
       'price_satisfaction', 'overall_satisfaction',
       'competitor_offers_received', 'price_sensitivity_score',
       'is_festival_season', 'monsoon_impact', 'churn_probability', 'churn'],
      dtype='str')

# To Know the Data Types of all Columns

In [19]:
df.dtypes

customer_id                       str
name                              str
phone                           int64
gender                            str
age                             int64
city                              str
state                             str
pincode                         int64
city_tier                         str
profession                        str
annual_income_lakhs           float64
is_married                       bool
has_children                     bool
num_dependents                  int64
operator                          str
plan_type                         str
monthly_charges                 int64
is_prepaid                       bool
tenure_months                   int64
total_charges                   int64
data_usage_gb                   int64
voice_minutes                   int64
sms_count                       int64
has_internet                     bool
has_ott_bundle                   bool
payment_method                    str
payment_delays_last_6m          int64
primary_language                  str
prefers_regional_support         bool
support_calls_last_month        int64
network_satisfaction            int64
price_satisfaction              int64
overall_satisfaction            int64
competitor_offers_received      int64
price_sensitivity_score         int64
is_festival_season               bool
monsoon_impact                   bool
churn_probability             float64
churn                             str
dtype: object

# TO Know info of all Columns

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 39 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   customer_id                 10000 non-null  str
 1   name                        10000 non-null  str
 2   phone                       10000 non-null  int64
 3   gender                      10000 non-null  str
 4   age                         10000 non-null  int64
 5   city                        10000 non-null  str
 6   state                       10000 non-null  str
 7   pincode                     10000 non-null  int64
 8   city_tier                   10000 non-null  str
 9   profession                  10000 non-null  str
 10  annual_income_lakhs         10000 non-null  float64
 11  is_married                  10000 non-null  bool
 12  has_children                10000 non-null  bool
 13  num_dependents              10000 non-null  int64
 14  operator                    10000 non-null  str
 15  plan_type                   10000 non-null  str
 16  monthly_charges             10000 non-null  int64
 17  is_prepaid                  10000 non-null  bool
 18  tenure_months               10000 non-null  int64
 19  total_charges               10000 non-null  int64
 20  data_usage_gb               10000 non-null  int64
 21  voice_minutes               10000 non-null  int64
 22  sms_count                   10000 non-null  int64
 23  has_internet                10000 non-null  bool
 24  has_ott_bundle              10000 non-null  bool
 25  payment_method              10000 non-null  str
 26  payment_delays_last_6m      10000 non-null  int64
 27  primary_language            10000 non-null  str
 28  prefers_regional_support    10000 non-null  bool
 29  support_calls_last_month    10000 non-null  int64
 30  network_satisfaction        10000 non-null  int64
 31  price_satisfaction          10000 non-null  int64
 32  overall_satisfaction        10000 non-null  int64
 33  competitor_offers_received  10000 non-null  int64
 34  price_sensitivity_score     10000 non-null  int64
 35  is_festival_season          10000 non-null  bool
 36  monsoon_impact              10000 non-null  bool
 37  churn_probability           10000 non-null  float64
 38  churn                       10000 non-null  str
dtypes: bool(8), float64(2), int64(17), str(12)
memory usage: 2.4 MB

#  TO know the Statistical info about the Data

In [21]:
df.describe()

,phone,age,pincode,annual_income_lakhs,num_dependents,monthly_charges,tenure_months,total_charges,data_usage_gb,voice_minutes,sms_count,payment_delays_last_6m,support_calls_last_month,network_satisfaction,price_satisfaction,overall_satisfaction,competitor_offers_received,price_sensitivity_score,churn_probability
count,1.000000e+04,10000.00000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.0000,10000.000000,10000.000000,10000.000000,10000.000000
mean,9.180055e+11,32.39120,551178.59770,16.492242,1.586000,545.518300,17.497600,9490.395300,29.383100,301.906500,55.273400,0.498100,0.795800,5.461600,5.5142,5.503900,2.497200,5.524500,0.492457
std,1.161323e+09,10.68862,259140.98167,12.488931,1.746113,497.291425,17.670479,15559.620904,20.874384,244.881275,26.361941,0.701745,0.892963,2.869068,2.8621,2.876945,1.721304,2.863114,0.264990
min,9.160000e+11,18.00000,100009.00000,2.000000,0.000000,99.000000,1.000000,100.000000,1.000000,50.000000,10.000000,0.000000,0.000000,1.000000,1.0000,1.000000,0.000000,1.000000,0.000000
25%,9.169956e+11,24.00000,326069.25000,7.090000,0.000000,238.000000,5.000000,1687.000000,14.000000,121.000000,32.750000,0.000000,0.000000,3.000000,3.0000,3.000000,1.000000,3.000000,0.294000
50%,9.180040e+11,32.00000,554250.00000,13.050000,1.000000,418.000000,12.000000,4532.000000,25.000000,235.000000,55.000000,0.000000,1.000000,5.000000,6.0000,5.000000,3.000000,6.000000,0.485000
75%,9.190232e+11,40.00000,774458.75000,22.382500,3.000000,665.000000,24.000000,10944.000000,39.000000,411.000000,78.000000,1.000000,1.000000,8.000000,8.0000,8.000000,4.000000,8.000000,0.685000
max,9.199999e+11,77.00000,999963.00000,67.470000,7.000000,2999.000000,160.000000,279110.000000,172.000000,2403.000000,100.000000,5.000000,7.000000,10.000000,10.0000,10.000000,5.000000,10.000000,1.000000

# To know no of columns and rows

In [22]:
df.shape # we have 10000 rows and 39 columns

(10000, 39)

# To Remove Unnecessary Columns

In [23]:
df.head()

,customer_id,name,phone,gender,age,city,state,pincode,city_tier,profession,annual_income_lakhs,is_married,has_children,num_dependents,operator,plan_type,monthly_charges,is_prepaid,tenure_months,total_charges,data_usage_gb,voice_minutes,sms_count,has_internet,has_ott_bundle,payment_method,payment_delays_last_6m,primary_language,prefers_regional_support,support_calls_last_month,network_satisfaction,price_satisfaction,overall_satisfaction,competitor_offers_received,price_sensitivity_score,is_festival_season,monsoon_impact,churn_probability,churn
0,IND000001,Arjun Bhatt,918332181960,Male,37,Indore,Maharashtra,198246,Tier 2,Student,2.00,True,True,1,Jio,Basic,282,True,32,9024,22,298,93,True,True,UPI,0,Punjabi,True,0,1,3,2,1,4,False,False,0.683,Yes
1,IND000002,Kavya Bose,918940781618,Female,44,Kolkata,West Bengal,969693,Tier 1,Government Employee,26.18,True,False,2,Airtel,Standard,322,True,27,8694,44,50,94,True,True,Debit Card,0,English,False,0,4,2,5,2,3,False,False,0.498,Yes
2,IND000003,Ramesh Desai,917832764835,Male,25,Bhopal,Maharashtra,340174,Tier 2,Business Owner,7.09,False,False,0,BSNL,Standard,504,True,2,1008,27,126,44,True,False,Credit Card,1,English,False,1,6,4,9,5,8,False,False,0.657,Yes
3,IND000004,Geeta Tiwari,919532871012,Female,43,Faridabad,Maharashtra,930555,Tier 2,Government Employee,17.33,True,True,6,Airtel,Premium,882,False,7,6174,29,480,11,True,True,UPI,0,Hindi,False,0,6,2,9,0,5,False,False,0.489,No
4,IND000005,Shubham Das,917252880957,Male,26,Mumbai,Maharashtra,217301,Tier 1,Private Employee,9.15,False,False,0,Vi,Standard,421,True,7,2947,51,383,17,True,True,Net Banking,1,Hindi,False,0,2,9,10,3,9,False,False,0.266,No

In [24]:
df.head()

,customer_id,name,phone,gender,age,city,state,pincode,city_tier,profession,annual_income_lakhs,is_married,has_children,num_dependents,operator,plan_type,monthly_charges,is_prepaid,tenure_months,total_charges,data_usage_gb,voice_minutes,sms_count,has_internet,has_ott_bundle,payment_method,payment_delays_last_6m,primary_language,prefers_regional_support,support_calls_last_month,network_satisfaction,price_satisfaction,overall_satisfaction,competitor_offers_received,price_sensitivity_score,is_festival_season,monsoon_impact,churn_probability,churn
0,IND000001,Arjun Bhatt,918332181960,Male,37,Indore,Maharashtra,198246,Tier 2,Student,2.00,True,True,1,Jio,Basic,282,True,32,9024,22,298,93,True,True,UPI,0,Punjabi,True,0,1,3,2,1,4,False,False,0.683,Yes
1,IND000002,Kavya Bose,918940781618,Female,44,Kolkata,West Bengal,969693,Tier 1,Government Employee,26.18,True,False,2,Airtel,Standard,322,True,27,8694,44,50,94,True,True,Debit Card,0,English,False,0,4,2,5,2,3,False,False,0.498,Yes
2,IND000003,Ramesh Desai,917832764835,Male,25,Bhopal,Maharashtra,340174,Tier 2,Business Owner,7.09,False,False,0,BSNL,Standard,504,True,2,1008,27,126,44,True,False,Credit Card,1,English,False,1,6,4,9,5,8,False,False,0.657,Yes
3,IND000004,Geeta Tiwari,919532871012,Female,43,Faridabad,Maharashtra,930555,Tier 2,Government Employee,17.33,True,True,6,Airtel,Premium,882,False,7,6174,29,480,11,True,True,UPI,0,Hindi,False,0,6,2,9,0,5,False,False,0.489,No
4,IND000005,Shubham Das,917252880957,Male,26,Mumbai,Maharashtra,217301,Tier 1,Private Employee,9.15,False,False,0,Vi,Standard,421,True,7,2947,51,383,17,True,True,Net Banking,1,Hindi,False,0,2,9,10,3,9,False,False,0.266,No

# To know no of unique values in each column

In [25]:
df.nunique().sort_values(ascending=False)

customer_id                   10000
phone                         10000
pincode                        9950
total_charges                  6172
name                           4033
annual_income_lakhs            3607
monthly_charges                1478
voice_minutes                  1035
churn_probability               999
data_usage_gb                   137
tenure_months                   118
sms_count                        91
age                              57
city                             48
profession                       10
price_sensitivity_score          10
overall_satisfaction             10
network_satisfaction             10
price_satisfaction               10
primary_language                  9
state                             9
support_calls_last_month          8
num_dependents                    8
competitor_offers_received        6
payment_method                    6
payment_delays_last_6m            6
operator                          5
plan_type                         4
city_tier                         3
gender                            2
has_children                      2
is_prepaid                        2
is_married                        2
has_ott_bundle                    2
has_internet                      2
prefers_regional_support          2
is_festival_season                2
monsoon_impact                    2
churn                             2
dtype: int64

# Remove Columns

In [26]:
df.drop(columns=["customer_id","phone","pincode"],inplace=True)

In [27]:
df.shape

(10000, 36)

# To see Missing values in each Column

In [28]:
df.isnull() #returns true/fasle
df.isnull().sum() # NO nulls are found

name                          0
gender                        0
age                           0
city                          0
state                         0
city_tier                     0
profession                    0
annual_income_lakhs           0
is_married                    0
has_children                  0
num_dependents                0
operator                      0
plan_type                     0
monthly_charges               0
is_prepaid                    0
tenure_months                 0
total_charges                 0
data_usage_gb                 0
voice_minutes                 0
sms_count                     0
has_internet                  0
has_ott_bundle                0
payment_method                0
payment_delays_last_6m        0
primary_language              0
prefers_regional_support      0
support_calls_last_month      0
network_satisfaction          0
price_satisfaction            0
overall_satisfaction          0
competitor_offers_received    0
price_sensitivity_score       0
is_festival_season            0
monsoon_impact                0
churn_probability             0
churn                         0
dtype: int64

# To see Duplicate Rows

In [29]:
df.duplicated()  # no duplicates found

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [30]:
df.duplicated().sum()

np.int64(0)

In [31]:
# to see specific  column duplicate rows

In [32]:
df["name"].duplicated().sum()  # 5967 name are same

np.int64(5967)

In [33]:
# to see those name by rows

In [34]:
df["name"].duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996     True
9997     True
9998     True
9999    False
Name: name, Length: 10000, dtype: bool

In [35]:
df[df["name"].duplicated(keep=False)] # returns all occurences of duplicate name including first name..

,name,gender,age,city,state,city_tier,profession,annual_income_lakhs,is_married,has_children,num_dependents,operator,plan_type,monthly_charges,is_prepaid,tenure_months,total_charges,data_usage_gb,voice_minutes,sms_count,has_internet,has_ott_bundle,payment_method,payment_delays_last_6m,primary_language,prefers_regional_support,support_calls_last_month,network_satisfaction,price_satisfaction,overall_satisfaction,competitor_offers_received,price_sensitivity_score,is_festival_season,monsoon_impact,churn_probability,churn
0,Arjun Bhatt,Male,37,Indore,Maharashtra,Tier 2,Student,2.00,True,True,1,Jio,Basic,282,True,32,9024,22,298,93,True,True,UPI,0,Punjabi,True,0,1,3,2,1,4,False,False,0.683,Yes
1,Kavya Bose,Female,44,Kolkata,West Bengal,Tier 1,Government Employee,26.18,True,False,2,Airtel,Standard,322,True,27,8694,44,50,94,True,True,Debit Card,0,English,False,0,4,2,5,2,3,False,False,0.498,Yes
2,Ramesh Desai,Male,25,Bhopal,Maharashtra,Tier 2,Business Owner,7.09,False,False,0,BSNL,Standard,504,True,2,1008,27,126,44,True,False,Credit Card,1,English,False,1,6,4,9,5,8,False,False,0.657,Yes
3,Geeta Tiwari,Female,43,Faridabad,Maharashtra,Tier 2,Government Employee,17.33,True,True,6,Airtel,Premium,882,False,7,6174,29,480,11,True,True,UPI,0,Hindi,False,0,6,2,9,0,5,False,False,0.489,No
4,Shubham Das,Male,26,Mumbai,Maharashtra,Tier 1,Private Employee,9.15,False,False,0,Vi,Standard,421,True,7,2947,51,383,17,True,True,Net Banking,1,Hindi,False,0,2,9,10,3,9,False,False,0.266,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9993,Isha Verma,Female,18,Faridabad,Maharashtra,Tier 2,Farmer,4.46,False,False,3,Airtel,Basic,153,True,5,765,51,271,90,True,True,UPI,0,Hindi,True,0,9,4,10,1,1,False,False,0.587,Yes
9994,Sneha Patel,Female,39,Jaipur,Rajasthan,Tier 1,Others,12.73,True,True,5,Airtel,Basic,158,True,1,158,31,50,69,True,False,UPI,3,English,False,0,5,2,4,0,4,False,False,0.566,Yes
9996,Tanya Srivastava,Female,33,Chennai,Tamil Nadu,Tier 1,IT Professional,41.44,True,False,3,Airtel,Premium,896,True,11,9856,25,392,52,False,True,UPI,0,Tamil,False,1,1,8,9,4,5,False,False,0.428,No
9997,Rashmi Bose,Female,31,Mumbai,Maharashtra,Tier 1,Private Employee,7.93,False,False,0,Jio,Basic,181,False,15,2715,5,182,85,True,False,UPI,0,English,False,0,6,3,9,1,1,False,False,0.273,No
9998,Geeta Shah,Female,29,Vasai,Maharashtra,Tier 2,Retired,10.46,True,True,2,BSNL,Basic,125,False,20,2500,57,65,84,True,True,Debit Card,0,Hindi,False,1,5,2,10,0,5,False,False,0.243,No

In [36]:
df[df["name"].duplicated()]

,name,gender,age,city,state,city_tier,profession,annual_income_lakhs,is_married,has_children,num_dependents,operator,plan_type,monthly_charges,is_prepaid,tenure_months,total_charges,data_usage_gb,voice_minutes,sms_count,has_internet,has_ott_bundle,payment_method,payment_delays_last_6m,primary_language,prefers_regional_support,support_calls_last_month,network_satisfaction,price_satisfaction,overall_satisfaction,competitor_offers_received,price_sensitivity_score,is_festival_season,monsoon_impact,churn_probability,churn
108,Shubham Mukherjee,Male,22,Pune,Maharashtra,Tier 1,Private Employee,19.49,False,False,4,Vi,Premium,694,True,8,5552,24,84,67,True,True,Net Banking,0,English,False,0,5,10,9,5,2,True,False,0.184,No
123,Tarun Ghosh,Male,28,Agra,Maharashtra,Tier 3,IT Professional,17.30,False,False,0,Jio,Premium,852,True,19,16188,69,50,31,True,True,Digital Wallet,0,Hindi,False,3,1,9,10,3,4,False,False,0.632,Yes
179,Pradeep Ghosh,Male,37,Aligarh,Maharashtra,Tier 3,IT Professional,15.33,False,False,0,Airtel,Standard,458,True,61,27938,13,74,15,True,True,UPI,1,Tamil,True,0,1,2,4,2,1,False,False,0.681,Yes
198,Shubham Das,Male,34,Hyderabad,Telangana,Tier 1,Retired,21.47,False,False,0,Vi,Premium,993,True,21,20853,18,773,90,True,True,Credit Card,0,Hindi,False,0,8,8,7,0,1,True,False,0.058,No
241,Nikhil Iyer,Male,49,Mumbai,Maharashtra,Tier 1,Homemaker,8.93,True,True,4,Vi,Basic,185,True,7,1295,9,221,65,True,True,UPI,0,English,False,0,8,5,9,0,9,False,False,0.000,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9993,Isha Verma,Female,18,Faridabad,Maharashtra,Tier 2,Farmer,4.46,False,False,3,Airtel,Basic,153,True,5,765,51,271,90,True,True,UPI,0,Hindi,True,0,9,4,10,1,1,False,False,0.587,Yes
9994,Sneha Patel,Female,39,Jaipur,Rajasthan,Tier 1,Others,12.73,True,True,5,Airtel,Basic,158,True,1,158,31,50,69,True,False,UPI,3,English,False,0,5,2,4,0,4,False,False,0.566,Yes
9996,Tanya Srivastava,Female,33,Chennai,Tamil Nadu,Tier 1,IT Professional,41.44,True,False,3,Airtel,Premium,896,True,11,9856,25,392,52,False,True,UPI,0,Tamil,False,1,1,8,9,4,5,False,False,0.428,No
9997,Rashmi Bose,Female,31,Mumbai,Maharashtra,Tier 1,Private Employee,7.93,False,False,0,Jio,Basic,181,False,15,2715,5,182,85,True,False,UPI,0,English,False,0,6,3,9,1,1,False,False,0.273,No
9998,Geeta Shah,Female,29,Vasai,Maharashtra,Tier 2,Retired,10.46,True,True,2,BSNL,Basic,125,False,20,2500,57,65,84,True,True,Debit Card,0,Hindi,False,1,5,2,10,0,5,False,False,0.243,No

In [37]:
df.drop(columns=['name'],inplace=True)

In [38]:
df.shape

(10000, 35)

# check outliers

In [39]:
Q1 = df['age'].quantile(0.25)
Q3 = df['age'].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[(df['age'] < lower_bound) |
              (df['age'] > upper_bound)]

print(outliers)

      gender  age             city          state city_tier  \
319   Female   65            Delhi          Delhi    Tier 1
902     Male   71    Visakhapatnam    Maharashtra    Tier 2
1561  Female   67           Jaipur      Rajasthan    Tier 1
1645    Male   77         Vadodara    Maharashtra    Tier 2
1816    Male   67            Delhi          Delhi    Tier 1
2838    Male   67         Bareilly    Maharashtra    Tier 3
2889  Female   66           Ranchi    Maharashtra    Tier 2
3772    Male   65        Bangalore      Karnataka    Tier 1
3939    Male   72          Jodhpur    Maharashtra    Tier 3
4487  Female   65            Surat        Gujarat    Tier 1
4772    Male   73       Chandigarh    Maharashtra    Tier 3
4777  Female   73            Vasai    Maharashtra    Tier 2
5659  Female   67           Jaipur      Rajasthan    Tier 1
6430  Female   67         Amritsar    Maharashtra    Tier 2
6893    Male   66  Tiruchirappalli    Maharashtra    Tier 3
7492  Female   65          Lucknow  Uttar Pradesh    Tier 1
7566  Female   70       Aurangabad    Maharashtra    Tier 2
7604  Female   68            Vasai    Maharashtra    Tier 2
7728  Female   67       Vijayawada    Maharashtra    Tier 3
8379    Male   65        Hyderabad      Telangana    Tier 1
8504    Male   66          Lucknow  Uttar Pradesh    Tier 1
8757    Male   66         Amritsar    Maharashtra    Tier 2
9442    Male   69    Visakhapatnam    Maharashtra    Tier 2

               profession  annual_income_lakhs  is_married  has_children  \
319               Student                 8.94       False         False
902       IT Professional                33.97       False         False
1561     Private Employee                13.72        True          True
1645               Farmer                 8.05        True          True
1816            Homemaker                 3.11        True         False
2838               Farmer                 5.03        True         False
2889              Retired                 6.51        True         False
3772     Private Employee                28.51        True         False
3939      IT Professional                28.03       False         False
4487     Private Employee                19.80        True         False
4772      IT Professional                 6.27        True          True
4777     Private Employee                11.65        True         False
5659       Business Owner                30.41        True         False
6430            Homemaker                 7.37       False         False
6893              Student                 2.00        True         False
7492            Homemaker                12.45        True          True
7566            Homemaker                 2.76       False         False
7604  Government Employee                24.30        True          True
7728  Government Employee                 3.52       False         False
8379            Homemaker                 2.92        True          True
8504  Government Employee                43.85        True         False
8757     Private Employee                17.43        True         False
9442       Business Owner                37.46       False         False

      num_dependents operator plan_type  monthly_charges  is_prepaid  \
319                0   Airtel  Standard              430        True
902                0      Jio   Premium              884        True
1561               1      Jio     Basic              226       False
1645               4      Jio     Basic              289        True
1816               0   Airtel     Basic              214       False
2838               0   Airtel  Standard              546        True
2889               0   Airtel  Standard              314       False
3772               1     BSNL   Premium              945        True
3939               0       Vi  Standard              376        True
4487               0       Vi   Premium              985       False
4772               2       Vi  Standard              342       False
4777               0      Jio     Basic              110        True
5659               0      Jio   Premium              835        True
6430               0       Vi  Standard              595        True
6893               0   Airtel     Basic              215        True
7492               2       Vi     Basic              179        True
7566               0      Jio     Basic              210        True
7604               5      Jio   Premium              695        True
7728               2   Airtel     Basic              265        True
8379               7      Jio     Basic              105        True
8504               0       Vi   Premium              928        True
8757               3      Jio   Premium              665        True
9442               0       Vi   Premium              738        True

      tenure_months  total_charges  data_usage_gb  voice_minutes  sms_count  \
319               4           1720             31            466         66
902              26          22984             22            194         41
1561              4            904             35            527         65
1645              4           1156             31            426         29
1816             57          12198             13            206         10
2838             41          22386             10            155         74
2889              1            314             29            156         28
3772             33          31185             31            581         95
3939             12           4512             31            121         17
4487              3           2955             43            290         41
4772             27           9234             50            209         84
4777              1            110             25            357         19
5659             41          34235             17            109         39
6430             16           9520              6             50         93
6893              2            430             17             81         25
7492              8           1432              4             59         27
7566              1            210             34             69         95
7604              5           3475             62            485         39
7728              6           1590             14            346         18
8379             11           1155             28             62         27
8504              3           2784             80            347         76
8757              4           2660              6            558         38
9442              4           2952              4            104         91

      has_internet  has_ott_bundle  payment_method  payment_delays_last_6m  \
319           True            True             UPI                       0
902           True           False            Cash                       0
1561          True            True      Debit Card                       0
1645          True            True     Net Banking                       0
1816          True           False             UPI                       0
2838          True           False             UPI                       0
2889         False           False      Debit Card                       0
3772          True           False  Digital Wallet                       2
3939          True           False             UPI                       2
4487          True            True      Debit Card                       1
4772          True            True     Net Banking                       1
4777          True            True      Debit Card                       1
5659          True           False            Cash                       0
6430          True           False      Debit Card                       1
6893          True           False            Cash                       2
7492          True            True             UPI                       1
7566          True            True     Net Banking                       0
7604          True           False             UPI                       1
7728         False           False            Cash                       1
8379          True           False     Credit Card                       0
8504          True            True            Cash                       0
8757          True            True      Debit Card                       0
9442          True            True  Digital Wallet                       1

     primary_language  prefers_regional_support  support_calls_last_month  \
319             Hindi                      True                         3
902           Marathi                     False                         0
1561            Hindi                      True                         2
1645          Marathi                      True                         1
1816          English                     False                         2
2838            Hindi                     False                         1
2889            Tamil                     False                         0
3772          English                     False                         0
3939          English                     False                         0
4487            Hindi                      True                         0
4772          Marathi                      True                         1
4777          Punjabi                      True                         1
5659            Hindi                     False                         0
6430            Tamil                      True                         1
6893            Tamil                      True                         0
7492          English                     False                         0
7566            Hindi                      True                         1
7604          English                     False                         1
7728            Hindi                      True                         0
8379            Hindi                     False                         1
8504            Hindi                      True                         0
8757            Tamil                      True                         0
9442          English                     False                         1

      network_satisfaction  price_satisfaction  overall_satisfaction  \
319                      1                   6                    10
902                      9                   3                     6
1561                     4                   3                     3
1645                    10                   6                     8
1816                     9                   3                     4
2838                     8                   5                     8
2889                     8                  10                     7
3772                     2                  10                     7
3939                    10                   2                     5
4487                     4                  10                     7
4772                    10                   9                     2
4777                     7                   7                     8
5659                     2                   6                     8
6430                     1                   4                     5
6893                     1                   4                     7
7492                     2                   6                     9
7566                     4                   1                     3
7604                     5                   1                     6
7728                     9                   7                    10
8379                     9                   5                     1
8504                    10                   9                     1
8757                     3                  10                     3
9442                     1                   9                     3

      competitor_offers_received  price_sensitivity_score  is_festival_season  \
319                            4                        3               False
902                            1                        7                True
1561                           4                        7               False
1645                           3                        8               False
1816                           1                        1               False
2838                           4                        8               False
2889                           4                        3               False
3772                           4                        6               False
3939                           2                        3               False
4487                           3                       10               False
4772                           1                        7               False
4777                           3                        1                True
5659                           1                        4               False
6430                           0                        9               False
6893                           4                        3               False
7492                           0                        2               False
7566                           3                        6                True
7604                           1                        9               False
7728                           4                       10                True
8379                           2                        4               False
8504                           5                        1                True
8757                           4                        5               False
9442                           0                        5                True

      monsoon_impact  churn_probability churn
319            False              0.876   Yes
902            False              0.154    No
1561           False              1.000   Yes
1645           False              0.258   Yes
1816           False              0.271    No
2838           False              0.312    No
2889           False              0.511    No
3772           False              0.158   Yes
3939           False              0.523    No
4487           False              0.712   Yes
4772           False              0.011    No
4777           False              0.211   Yes
5659           False              0.013    No
6430           False              0.511   Yes
6893           False              1.000   Yes
7492           False              0.235    No
7566           False              1.000   Yes
7604           False              0.689   Yes
7728           False              0.237    No
8379           False              0.158    No
8504           False              0.384   Yes
8757           False              0.614   Yes
9442           False              0.607   Yes

In [40]:
print(outliers.shape[0])

23

# Transfer to  postgresql

In [41]:
# load dataframe into postgresql
#df.to_sql("Telecom_Customer_Data", engine, if_exists="replace", index=False)

In [42]:
import pandas as pd
from sqlalchemy import create_engine
engine = create_engine("postgresql://postgres:7583@localhost:5432/users")

In [54]:
df.columns=df.columns.str.lower()

In [52]:
# load dataframe into postgresql
df.to_sql(
    name='Telecom_users',
    con=engine,
    if_exists='replace',
    index=False
)

660

In [53]:
df.shape

(10000, 35)